# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageCorner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImageCorner
   pod 'SDWebImage'
   #pod 'YYCache'

  target 'ImageCornerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageCornerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
